// Shared column conventions (data-model-spec §0, ruled 15 Aug 2026).
//
// Forty tables inherit these. They exist as builders rather than as a style
// guide so the correct type is the easy one to reach for and the wrong one
// takes deliberate effort. A convention enforced by review is a convention
// that erodes; a convention enforced by construction does not.

import { sql } from "drizzle-orm";
import {
  date,
  numeric,
  timestamp,
  uuid,
  type PgColumnBuilderBase,
} from "drizzle-orm/pg-core";

/**
 * Primary key: UUIDv7, generated by Postgres.
 *
 * Time-ordered, so index locality holds as tables grow (UUIDv4 scatters
 * B-tree inserts). Not sequential integers: household ids appear in URLs and
 * logs, and sequential ids leak volume. The default lives in the database
 * rather than in application code, so a second writer cannot forget it.
 * Postgres 18 provides uuidv7() natively.
 */
export const uuidv7Pk = () =>
  uuid("id").primaryKey().default(sql`uuidv7()`);

/** A UUIDv7 foreign-key column, same generation rules, no default. */
export const uuidRef = (name: string) => uuid(name);

/**
 * Money: numeric(14,2). Never float, never for percentages.
 *
 * Binary floating point cannot represent 0.10. Sum enough of them and Kept is
 * wrong by cents, which in a product whose entire claim is
 * "Income − Spending = Kept" is a broken promise rather than a rounding
 * artifact. numeric is exact decimal.
 *
 * PERCENTAGES ARE NOT MONEY (ruled 15 Aug 2026). Margin is a computed ratio,
 * not a stored dollar amount, and reaching for money() to hold one is the
 * mistake this note exists to prevent. Use percentage() below, and read its
 * comment first: Margin is usually not stored at all.
 *
 * SIGN CONVENTION, STATED ONCE FOR THE WHOLE SYSTEM (data-model-spec §0):
 * Plaid's convention is preserved end to end. POSITIVE = OUTFLOW (expense),
 * NEGATIVE = INFLOW. No layer flips signs. The failure this prevents is two
 * layers each "helpfully" normalizing, and a household's income rendering as
 * spending.
 */
export const money = (name: string) => numeric(name, { precision: 14, scale: 2 });

/**
 * A computed ratio stored as a percentage. Read this before using it.
 *
 * Margin (kept / income, rendered as %) is normally NOT a column: it is
 * computed at read time by the P&L engine, because it is derived from two
 * stored figures and storing it invites the two to disagree.
 *
 * The ledger spec's guard is a COMPUTED-VALUE RULE, NOT A COLUMN CONSTRAINT:
 * Margin is computed only when income > 0 and |kept / income| <= 10;
 * otherwise it is null. A ratio beyond 1000% is nonsensical for a monthly
 * household P&L and renders as absent rather than absurd. That rule lives in
 * the engine (M6a), not in a CHECK constraint, because it governs whether a
 * value is produced at all rather than which values a column may hold.
 *
 * Naming, per the ledger spec's correction for the rebuild: the dollar result
 * is `kept` and the percentage is `margin_pct`. Base44 called them `margin`
 * and `margin_rate`, which is the exact confusion the locked vocabulary
 * exists to prevent. Do not carry those names across.
 *
 * Use this only for a genuinely stored target or snapshot, such as
 * household_goals.margin_target_pct, where a household stated a number.
 */
export const percentage = (name: string) => numeric(name, { precision: 6, scale: 3 });

/**
 * A bank day, not an instant.
 *
 * A purchase "on June 3" is on June 3 regardless of the household's timezone
 * or the sync's timezone. Storing it as a timestamp invites off-by-one-day
 * errors at month boundaries, which corrupts a monthly close. Household
 * timezone lives on households and scheduled sends compute in it; this column
 * type deliberately carries no timezone semantics.
 */
export const bankDay = (name: string) => date(name);

/** A real instant. Everything that is not a bank day. */
export const instant = (name: string) => timestamp(name, { withTimezone: true });

/**
 * The household scope column. Present on every table except global and system
 * tables.
 *
 * This is the RLS predicate: without it on the row, row-level security has
 * nothing to filter on. Its absence on a table is a deliberate statement that
 * the table is global, and should be obvious in review.
 */
export const householdId = () => uuid("household_id").notNull();

/**
 * created_at and updated_at, on every table.
 *
 * updated_at is maintained by trigger (see the touch_updated_at function in
 * the first migration) rather than by application code, so a write path that
 * forgets it cannot produce a stale value.
 */
export const timestamps = (): Record<string, PgColumnBuilderBase> => ({
  createdAt: instant("created_at").notNull().defaultNow(),
  updatedAt: instant("updated_at").notNull().defaultNow(),
});
