-- Reverses 0008_rls.sql.
DROP POLICY IF EXISTS "household_isolation" ON "members";
DROP POLICY IF EXISTS "sync_worker_access" ON "members";
ALTER TABLE "members" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "household_isolation" ON "invitations";
DROP POLICY IF EXISTS "sync_worker_access" ON "invitations";
ALTER TABLE "invitations" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "household_isolation" ON "trial_records";
DROP POLICY IF EXISTS "sync_worker_access" ON "trial_records";
ALTER TABLE "trial_records" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "household_isolation" ON "consent_records";
DROP POLICY IF EXISTS "sync_worker_access" ON "consent_records";
ALTER TABLE "consent_records" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "household_isolation" ON "plaid_items";
DROP POLICY IF EXISTS "sync_worker_access" ON "plaid_items";
ALTER TABLE "plaid_items" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "household_isolation" ON "financial_accounts";
DROP POLICY IF EXISTS "sync_worker_access" ON "financial_accounts";
ALTER TABLE "financial_accounts" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "household_isolation" ON "account_balance_snapshots";
DROP POLICY IF EXISTS "sync_worker_access" ON "account_balance_snapshots";
ALTER TABLE "account_balance_snapshots" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "household_isolation" ON "liability_details";
DROP POLICY IF EXISTS "sync_worker_access" ON "liability_details";
ALTER TABLE "liability_details" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "household_isolation" ON "provider_events";
DROP POLICY IF EXISTS "sync_worker_access" ON "provider_events";
ALTER TABLE "provider_events" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "household_isolation" ON "categories";
DROP POLICY IF EXISTS "sync_worker_access" ON "categories";
ALTER TABLE "categories" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "household_isolation" ON "transactions";
DROP POLICY IF EXISTS "sync_worker_access" ON "transactions";
ALTER TABLE "transactions" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "household_isolation" ON "merchant_corrections";
DROP POLICY IF EXISTS "sync_worker_access" ON "merchant_corrections";
ALTER TABLE "merchant_corrections" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "household_isolation" ON "category_rules";
DROP POLICY IF EXISTS "sync_worker_access" ON "category_rules";
ALTER TABLE "category_rules" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "household_isolation" ON "source_renames";
DROP POLICY IF EXISTS "sync_worker_access" ON "source_renames";
ALTER TABLE "source_renames" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "household_isolation" ON "commitments";
DROP POLICY IF EXISTS "sync_worker_access" ON "commitments";
ALTER TABLE "commitments" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "household_isolation" ON "household_goals";
DROP POLICY IF EXISTS "sync_worker_access" ON "household_goals";
ALTER TABLE "household_goals" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "household_isolation" ON "threads";
DROP POLICY IF EXISTS "sync_worker_access" ON "threads";
ALTER TABLE "threads" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "household_isolation" ON "messages";
DROP POLICY IF EXISTS "sync_worker_access" ON "messages";
ALTER TABLE "messages" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "household_isolation" ON "question_dispatches";
DROP POLICY IF EXISTS "sync_worker_access" ON "question_dispatches";
ALTER TABLE "question_dispatches" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "household_isolation" ON "known_context";
DROP POLICY IF EXISTS "sync_worker_access" ON "known_context";
ALTER TABLE "known_context" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "household_isolation" ON "tombstones";
DROP POLICY IF EXISTS "sync_worker_access" ON "tombstones";
ALTER TABLE "tombstones" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "household_isolation" ON "standing_instructions";
DROP POLICY IF EXISTS "sync_worker_access" ON "standing_instructions";
ALTER TABLE "standing_instructions" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "household_isolation" ON "tags";
DROP POLICY IF EXISTS "sync_worker_access" ON "tags";
ALTER TABLE "tags" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "household_isolation" ON "tag_members";
DROP POLICY IF EXISTS "sync_worker_access" ON "tag_members";
ALTER TABLE "tag_members" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "household_isolation" ON "decision_journal";
DROP POLICY IF EXISTS "sync_worker_access" ON "decision_journal";
ALTER TABLE "decision_journal" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "household_isolation" ON "handoffs";
DROP POLICY IF EXISTS "sync_worker_access" ON "handoffs";
ALTER TABLE "handoffs" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "household_isolation" ON "condition_states";
DROP POLICY IF EXISTS "sync_worker_access" ON "condition_states";
ALTER TABLE "condition_states" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "household_isolation" ON "calibration_bands";
DROP POLICY IF EXISTS "sync_worker_access" ON "calibration_bands";
ALTER TABLE "calibration_bands" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "household_isolation" ON "insight_ledger";
DROP POLICY IF EXISTS "sync_worker_access" ON "insight_ledger";
ALTER TABLE "insight_ledger" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "household_isolation" ON "receivables";
DROP POLICY IF EXISTS "sync_worker_access" ON "receivables";
ALTER TABLE "receivables" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "household_isolation" ON "artifacts";
DROP POLICY IF EXISTS "sync_worker_access" ON "artifacts";
ALTER TABLE "artifacts" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "household_isolation" ON "exports";
DROP POLICY IF EXISTS "sync_worker_access" ON "exports";
ALTER TABLE "exports" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "household_isolation" ON "llm_call_logs";
DROP POLICY IF EXISTS "sync_worker_access" ON "llm_call_logs";
ALTER TABLE "llm_call_logs" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "household_isolation" ON "llm_cache";
DROP POLICY IF EXISTS "sync_worker_access" ON "llm_cache";
ALTER TABLE "llm_cache" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "household_isolation" ON "stripe_subscriptions";
DROP POLICY IF EXISTS "sync_worker_access" ON "stripe_subscriptions";
ALTER TABLE "stripe_subscriptions" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "household_isolation" ON "households";
DROP POLICY IF EXISTS "sync_worker_access" ON "households";
ALTER TABLE "households" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON "members" FROM marginsheet_app;
REVOKE ALL ON "members" FROM marginsheet_sync;
REVOKE ALL ON "invitations" FROM marginsheet_app;
REVOKE ALL ON "invitations" FROM marginsheet_sync;
REVOKE ALL ON "trial_records" FROM marginsheet_app;
REVOKE ALL ON "trial_records" FROM marginsheet_sync;
REVOKE ALL ON "consent_records" FROM marginsheet_app;
REVOKE ALL ON "consent_records" FROM marginsheet_sync;
REVOKE ALL ON "financial_accounts" FROM marginsheet_app;
REVOKE ALL ON "financial_accounts" FROM marginsheet_sync;
REVOKE ALL ON "account_balance_snapshots" FROM marginsheet_app;
REVOKE ALL ON "account_balance_snapshots" FROM marginsheet_sync;
REVOKE ALL ON "liability_details" FROM marginsheet_app;
REVOKE ALL ON "liability_details" FROM marginsheet_sync;
REVOKE ALL ON "provider_events" FROM marginsheet_app;
REVOKE ALL ON "provider_events" FROM marginsheet_sync;
REVOKE ALL ON "categories" FROM marginsheet_app;
REVOKE ALL ON "categories" FROM marginsheet_sync;
REVOKE ALL ON "transactions" FROM marginsheet_app;
REVOKE ALL ON "transactions" FROM marginsheet_sync;
REVOKE ALL ON "merchant_corrections" FROM marginsheet_app;
REVOKE ALL ON "merchant_corrections" FROM marginsheet_sync;
REVOKE ALL ON "category_rules" FROM marginsheet_app;
REVOKE ALL ON "category_rules" FROM marginsheet_sync;
REVOKE ALL ON "source_renames" FROM marginsheet_app;
REVOKE ALL ON "source_renames" FROM marginsheet_sync;
REVOKE ALL ON "commitments" FROM marginsheet_app;
REVOKE ALL ON "commitments" FROM marginsheet_sync;
REVOKE ALL ON "household_goals" FROM marginsheet_app;
REVOKE ALL ON "household_goals" FROM marginsheet_sync;
REVOKE ALL ON "threads" FROM marginsheet_app;
REVOKE ALL ON "threads" FROM marginsheet_sync;
REVOKE ALL ON "messages" FROM marginsheet_app;
REVOKE ALL ON "messages" FROM marginsheet_sync;
REVOKE ALL ON "question_dispatches" FROM marginsheet_app;
REVOKE ALL ON "question_dispatches" FROM marginsheet_sync;
REVOKE ALL ON "known_context" FROM marginsheet_app;
REVOKE ALL ON "known_context" FROM marginsheet_sync;
REVOKE ALL ON "tombstones" FROM marginsheet_app;
REVOKE ALL ON "tombstones" FROM marginsheet_sync;
REVOKE ALL ON "standing_instructions" FROM marginsheet_app;
REVOKE ALL ON "standing_instructions" FROM marginsheet_sync;
REVOKE ALL ON "tags" FROM marginsheet_app;
REVOKE ALL ON "tags" FROM marginsheet_sync;
REVOKE ALL ON "tag_members" FROM marginsheet_app;
REVOKE ALL ON "tag_members" FROM marginsheet_sync;
REVOKE ALL ON "decision_journal" FROM marginsheet_app;
REVOKE ALL ON "decision_journal" FROM marginsheet_sync;
REVOKE ALL ON "handoffs" FROM marginsheet_app;
REVOKE ALL ON "handoffs" FROM marginsheet_sync;
REVOKE ALL ON "condition_states" FROM marginsheet_app;
REVOKE ALL ON "condition_states" FROM marginsheet_sync;
REVOKE ALL ON "calibration_bands" FROM marginsheet_app;
REVOKE ALL ON "calibration_bands" FROM marginsheet_sync;
REVOKE ALL ON "insight_ledger" FROM marginsheet_app;
REVOKE ALL ON "insight_ledger" FROM marginsheet_sync;
REVOKE ALL ON "receivables" FROM marginsheet_app;
REVOKE ALL ON "receivables" FROM marginsheet_sync;
REVOKE ALL ON "artifacts" FROM marginsheet_app;
REVOKE ALL ON "artifacts" FROM marginsheet_sync;
REVOKE ALL ON "exports" FROM marginsheet_app;
REVOKE ALL ON "exports" FROM marginsheet_sync;
REVOKE ALL ON "llm_call_logs" FROM marginsheet_app;
REVOKE ALL ON "llm_call_logs" FROM marginsheet_sync;
REVOKE ALL ON "llm_cache" FROM marginsheet_app;
REVOKE ALL ON "llm_cache" FROM marginsheet_sync;
REVOKE ALL ON "stripe_subscriptions" FROM marginsheet_app;
REVOKE ALL ON "stripe_subscriptions" FROM marginsheet_sync;
REVOKE ALL ON "households" FROM marginsheet_app;
REVOKE ALL ON "households" FROM marginsheet_sync;
REVOKE ALL ON "global_merchant_facts" FROM marginsheet_app;
REVOKE ALL ON "global_merchant_facts" FROM marginsheet_sync;
